### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by PattyToTheWatty** [TotalFreedom/TotalFreedomMod#545]
It Still doesnt work. Ive tried new versions of spigot compiled it and still. No.
Heres my errors:

net.minecraft.server.v1_8_R1.MinecraftServer;
import net.minecraft.server.v1_8_R1.PropertyManager;

Error With Net

![capture](https://cloud.githubusercontent.com/assets/11896861/7103783/bb631ad6-e0fb-11e4-9eb3-feeedd837759.JPG)

**Comment by PattyToTheWatty** [comment]
i have spigot 1.8 R01

**Comment by AlexFreedomMod** [comment]
Maybe its because of r01, did you try R02?

**Comment by PattyToTheWatty** [comment]
No i didnt try R02 could you maybe link it to me?

**Comment by AlexFreedomMod** [comment]
I dont know the link, but i do think build tools will give it to you

**Comment by AlexFreedomMod** [comment]
I will look for it

**Comment by AlexFreedomMod** [comment]
Hmm, it might be because it doesnt have it,

**Comment by JeromSar** [comment]
Can you ensure you are compiling with Spigot-Server, and not Spigot?

**Comment by AlexFreedomMod** [comment]
What?

**Comment by AlexFreedomMod** [comment]
Maybe the code is wrong

**Comment by Wild1145** [comment]
@AlexFreedomMod Please, for the love of god stop spamming, and if you are going to, at least make it vaguly productive, and not one line per bloody comment.

@PattyToTheWatty Are you using the spigot build that I sent you yesterday? If not if you can start by using that it would be helpful. Then change those imports to v1_8_R2 .blablabla

**Comment by AlexFreedomMod** [comment]
@Wild1145 commented 12 hours ago
Download http://gaming.superior-networks.com/jars/Spigot/Spigot-Server/target/spigot-1.8.3-R0.1-SNAPSHOT.jar and use that. Then change it from R1 to R2.

**Comment by PattyToTheWatty** [comment]
Ok, tell me if im doing it right.
Download spigot-server compile it with netbeans, go into serverinterface.java. And change R0.1 
To R0.2?

**Comment by Wild1145** [comment]
@PattyToTheWatty That should fix the issue, or at the very least allow the plugin to correctly compile.

**Comment by PattyToTheWatty** [comment]
Still no. :( i still get an server interface error and it wont build properly

**Comment by JeromSar** [comment]
@PattyToTheWatty Alright, please try the following:
* Redownload builtools.jar, save it to a new folder and run it to get Spigot-1.8.3.jar and SpigotAPI-1.8.3.jar
* Redownload TotalFreedomMod's source (lastest version compiles with Spigot-1.8.3)
* Download [TF-Essentials](https://github.com/TotalFreedom/TF-Essentials/releases) and [TF-WorldEdit](https://github.com/TotalFreedom/TF-WorldEdit/releases).
* Download [BukkitTelnet](https://github.com/TotalFreedom/BukkitTelnet)'s sourcefiles.
* Open Netbeans and compile BukkitTelnet with SpigotAPI-1.8.3.jar
* Open TotalFreedomMod and compile it with the following dependencies: (**Note**: All these dependencies should be tied to already present NetBeans "libraries" which may be nonexistent in your workspace)
  * Spigot-1.8.3.jar (The server, not the API)
  * BukkitTelnet
  * TF-WorldEdit
  * TF-Essentials

You should be all set from there. :)

**Comment by PattyToTheWatty** [comment]
OMG THANK YOU SO MUCH!!!

**Comment by iHoracio** [comment]
@PattyToTheWatty Redownload TFM, Import the new TFM-Master.
then add:
   BukkitLib.jar
   BukkitTelnet.jar
   Spigot.jar
   TF-WorldEdit
   TF-Essentials.
Watch xPacksGamingHD's (or others) videos for more information
